services:
  - docker

script:
- docker build -t rassol/gitlab_exporter:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push rassol/gitlab_exporter:latest
